export declare enum CarBrandsEnum {
    Toyota = "Toyota",
    Ford = "Ford",
    Renault = "Renault",
    Honda = "Honda",
    Chevrolet = "Chevrolet",
    Volkswagen = "Volkswagen",
    Nissan = "Nissan",
    BMW = "BMW",
    Mercedes = "Mercedes",
    Audi = "Audi",
    Tesla = "Tesla",
    Subaru = "Subaru",
    Hyundai = "Hyundai",
    Kia = "Kia",
    Mazda = "Mazda",
    Jeep = "Jeep",
    Lexus = "Lexus",
    Porsche = "Porsche",
    Jaguar = "Jaguar"
}
